#ifndef VOXGRAPH_FRONTEND_MEASUREMENT_PROCESSORS_GPS_PROCESSOR_H_
#define VOXGRAPH_FRONTEND_MEASUREMENT_PROCESSORS_GPS_PROCESSOR_H_

namespace voxgraph {
class GpsProcessor {
 public:
 private:
};
}  // namespace voxgraph

#endif  // VOXGRAPH_FRONTEND_MEASUREMENT_PROCESSORS_GPS_PROCESSOR_H_
